A00Protector:

  crash:
    handle-disconnect:
      enable: false
    kick-player:
      enable: false
    close-socket:
      enable: true
    crash-player:
      enable: false
    ban:
      enable: false

  ClearItemsOnGround:
    world: 'world'
    max-items: 300

  anti-vpn:
    enable: false
    checkip:
      enable: true
    country:
      enable: false
      list:
      - "Poland"
    isocode:
      enable: false
      list:
      - "PL"

  PagesLimiter-Two:
    enable: true
    limit: 15

  PagesLimiter:
    enable: true
    limit: 5

  CheckPing:
    enable: true
    limit: 1200

  ScoreBoard:
    enable: false

  nick-check:
    enable: true
    list:
    - "Stulejka"

  antybot:
    ping-motd:
      enable: true
    double-join:
      enable: false

  chat:
    enable: true
    bad-message:
      enable: true
      list:
      - "fuck"
    bad-command:
      enable: true
      list:
      - "/pl"
      - "/plugins"

  payload:
    enable: true

  exploits:
    pex:
      enable: true
    worldedit:
      enable: true
    redstone-lag-exploit:
      enable: true
      max-change: 60
    book-max-enchant-exploit:
      enable: true

CustomPayLoad:
  WorldDownloader:
    enable: true
  Forge:
    enable: false
  Checker:
    enable: true

  PacketLimit:
    enable: true
    limit: 20

ServerLagAndCrashDetector:
  enable: true
  Blocker:
    ArmAnimation:
      limit: 200
    BlockDig:
      limit: 160
    BlockPlace:
      limit: 80
    CloseWindow:
      limit: 80
    UseEntity:
      limit: 600
    BookEdit:
      limit: 5
    EnchantItem:
      limit: 50
    EntityAction:
      limit: 500
    HeldItemSlot:
      limit: 40
    Look:
      limit: 400
    Position:
      limit: 400
    ResourcePackStatus:
      limit: 50
    SetCreativeSlot:
      limit: 80
    Settings:
      limit: 50
    TabComplete:
      limit: 50
    Transaction:
      limit: 100
    UpdateSign:
      limit: 60
    WindowClick:
      limit: 80

