name: A00Protector
version: 2.7-Stable
author: KSCode.eu
main: eu.kscode.protector.basic.Main
website: 'https://discord.gg/3gFPgQ8'
depend: ['ProtocolLib']
description: This plugin protects your server :)
commands:
  Protector:
    aliases: [a00p, a00, antycrash, anticrash, protector, a00protector]
  Server:
    aliases: [info, information, informations]
  Memory:
    aliases: [ram]
      
      